app:
  frontEndUri: http://localhost:3000
  deleteExpiredTokensDelayMsec: 30000 # 30 seconds
  allowedOrigins:
    - ${app.frontEndUri}
    - https://auth.expo.io/@hasatori/ReactNativeFrontend
  authorizedRedirectUris:
    - ${app.frontEndUri}/oauth2/redirect
    - https://auth.expo.io/@hasatori/ReactNativeFrontend
  accountActivationUri: ${app.frontEndUri}/activate-account
  emailChangeConfirmationUri: ${app.frontEndUri}/confirm-email-change
  passwordResetUri: ${app.frontEndUri}/password-reset
  auth:
    accessTokenExpirationMsec: 300000 # 5 minutes
    refreshTokenExpirationMsec: 900000 # 15 minutes
    verificationTokenExpirationMsec: 60000 # 1 minute
